# Generated by Django 4.2.15 on 2025-05-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
